version: '3.8'
services:
  myapp:
    image: zihehuang33/lisayoga_server:latest
    ports:
      - "12010:443"
    depends_on: [db]
    networks:
      - app-network

  db:
    image: zihehuang33/lisayoga_database:latest
    ports:
      - "33004:3306"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge