
spring:
  datasource:
    druid:
      url: jdbc:mysql://db:3306/lisayoga?characterEncoding=utf-8&ti&useSSL=false&&serverTimezone=Asia/Shanghai
      username: lisayoga
      password: q980330
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 30000

logging:
  level:
    com.zihe.tams: info
