name: Deploy to AWS

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy: #name of the job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: |
          docker build -t zihehuang33/lisayoga_server:${{github.sha}} .
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push zihehuang33/lisayoga_server:${{ github.sha }}