name: Deploy to AWS

env:
  MY_APPNAME: lisayoga_server
on:
  push:
    branches: [ master ]

jobs:
  build: #name of the job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: |
          docker build -t zihehuang33/lisayoga_server:latest .
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push zihehuang33/lisayoga_server:latest

  deploy: # the name of job
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh command using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.MY_APPNAME }}:latest
          docker stop ${{ env.MY_APPNAME }} || true
          docker rm ${{ env.MY_APPNAME }} || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ env.MY_APPNAME }}:latest || true
          docker run --network lisayoga -d --name ${{ env.MY_APPNAME }} -p 80:80 ${{ secrets.DOCKER_USERNAME }}/${{ env.MY_APPNAME }}:latest